const mdpdf = require('mdpdf');
const path = require('path');
const fs = require('fs').promises;

// const DOCS_FOLDER = path.join(__dirname, '../docs/central_ledger');
const DOCS_FOLDER = path.join(__dirname, '../docs/account_lookup');
const FOLDER_NAME = path.basename(DOCS_FOLDER);
const TEMP_FILE = path.join(__dirname, 'combined.md');
const OUTPUT_DIR = path.join(__dirname, '../pdfs');

async function concatenateMarkdownFiles() {
    // Read all files in the docs folder
    const files = await fs.readdir(DOCS_FOLDER);

    // Filter for .md files
    const mdFiles = files.filter(file => file.endsWith('.md'));

    // Read and concatenate all markdown files
    let combinedContent = '';
    for (const file of mdFiles) {
        const filePath = path.join(DOCS_FOLDER, file);
        let content = await fs.readFile(filePath, 'utf-8');
        // Remove tbls generated footer
        content = content.replace(/> Generated by \[tbls\]\(https:\/\/github\.com\/k1LoW\/tbls\)/g, '');
        combinedContent += content + '\n\n';
    }

    // Write combined content to temporary file
    await fs.writeFile(TEMP_FILE, combinedContent);

    return TEMP_FILE;
}

async function convertToPdf() {
    try {
        // Ensure output directory exists
        await fs.mkdir(OUTPUT_DIR, { recursive: true });

        // Concatenate all markdown files
        const sourceFile = await concatenateMarkdownFiles();
        console.log('Combined markdown files into:', sourceFile);

        // Convert to PDF
        let options = {
            source: sourceFile,
            destination: path.join(OUTPUT_DIR, `${FOLDER_NAME}.pdf`),
            styles: path.join(__dirname, 'md-styles.css'),
            ghStyle: true,
            defaultStyle: true,
            pdf: {
                format: 'Tabloid',
                // orientation: 'landscape'
                orientation: 'portrait'
            }
        };

        const pdfPath = await mdpdf.convert(options);
        console.log('PDF Path:', pdfPath);

        // Clean up temporary file
        await fs.unlink(TEMP_FILE);
        console.log('Cleaned up temporary file');
    } catch (err) {
        console.error(err);
    }
}

convertToPdf();